management:
    security:
        enabled: false
security:
    basic:
        enabled: false
#Fix spring boot default security
    ignored: /**

spring:
    datasource:
        default-catalog: library
        jndi-name: jdbc/Library
        sql-script-encoding: UTF-8
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
                connection:
#                   Also need to add characterEncoding = UTF-8 for JDBC Connection Pool in case of external server
                    characterEncoding: utf-8
                    CharSet: utf-8
                    useUnicode: true
        show-sql: true


logging:
    file: logs/library_app.log
    pattern:
      file: "%d{HH:mm:ss} %-5p [%c] - %m%n"
    level:
        ROOT: error
        org.springframework: warn
        javax.faces: warn
        org.omnifaces: warn
        org.springframework.security: warn
        org.hibernate: trace
        org.hibernate.type.descriptor.sql: trace